### PR TITLE
Automatic deployment with GitHub Actions

### LINKED ISSUE #9: [Suggestion] Use GitHub Action to automatically deploy docs
If I'm not wrong you're using GitHub Pages to host the docs.

Wouldn't it be an option to use GitHub Actions to automatically build the HTML and deploy it to GitHub Pages? Then you wouldn't have to tidy up behind PRs (like mine... :D) and you wouldn't have the generated code inside the regular branches.

I saw this approach here and quite liked it:
https://github.com/Krzysztof-Cieslak/SampleWaypoint/blob/master/.github/workflows/docs.yml

You could change the trigger e.g. to:
```
on:
  push:
    branches:
      - master
```

What do you think? Are there reasons to not use this approach?

### PR DESCRIPTION
**Pull request by NicoVIII**
Hopefully closes #9 

I defined a workflow for GitHub Actions which automatically deploys changes in master branch to an orphan branch called gh-pages. Therefore after this is merged, a maintainer possibly has to **change the GitHub Pages setting** so the page will be deployed by the orphan branch and not longer from the docs folder.
To simplify things I moved build stuff out of the src folder and installed fornax as a local tool as well.
I tried to adjust the README.

I hope everything I did is okay and will work, I only tried the GitHub Action run, but it didn't deploy for me because I was in a fork.
https://github.com/NicoVIII/Avalonia.FuncUI.Docs/actions/runs/94329157

Please tell me if this is okay and we can try that or if I changed too much structure or anything.

### CODE REVIEW

**Comment by JaggerJo** [comment]
@NicoVIII Nice! This is definitely an improvement - Thanks for the Contribution  👍 

@AngelMunoz can you take a look ?

**Comment by AngelMunoz** [comment]
sure I will! but I think @JaggerJo needs to set up a secret on the actions page not entirely sure how that works but it is indeed asking for secret token (to have write access from CI I guess)

https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs/pull/13/files#diff-3c4be0fd2e06e22844033646c17f38a3R21

>This action runs on a fork and not found auth token, Skip deployment

I'll review it on my fork and see if I can make it work there

**Comment by NicoVIII** [comment]
Oh sorry, I forgot to change the used token.
This should have been `${{ secrets.GITHUB_TOKEN }}` and this should work, because this is a automatically generated token.
https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

I will commit that and try it again in my fork :)

**Comment by NicoVIII** [comment]
I guess it worked for me now.
https://github.com/NicoVIII/Avalonia.FuncUI.Docs/actions/runs/94552949

Here is the created orphaned branch:
https://github.com/NicoVIII/Avalonia.FuncUI.Docs/tree/gh-pages

And now I have my own version of the docs :D
https://nicoviii.github.io/Avalonia.FuncUI.Docs/

Sorry for the inconvenience!

**Comment by AngelMunoz** [comment]
indeed you are right I was just trying that! yup, It seems to work just fine :)

**Pull request merged**
