### PR TITLE
Set baseUrl depending on watch or build

### PR DESCRIPTION
**Pull request by NicoVIII**
To simplify working with the docs, I added conditional compilation so
that in WatchMode (dev) the url is "/" and in BuildMode (live) the url
is "/Avalonia.FuncUi.Docs/".

With that manual changes are no longer necessary to start working (I hope :smile:).

### CODE REVIEW

**Comment by AngelMunoz** [comment]
is this working for you?
I tried locally but either I'm doing something wrong or not sure what's happening
image

image

**Comment by NicoVIII** [comment]
Hmm, yeah.
I rebased the branch and it still works for me. I don't know if it makes a difference that I'm on a linux system?
On master it looks for me like for you, because the /Avalonia.FuncUI.Docs/ is used as baseurl which is wrong for local mode.

I will try to test it on windows tomorrow and see, if I can reproduce your issue and fix it.

**Comment by AngelMunoz** [comment]
yeah, it might be, which version of fornax cli are you using? (I'm on 0.12.0)

**Comment by NicoVIII** [comment]
I use the local tools defined in the tool-manifest, I tend to not install those tools globally ^.^
So 0.13.1 I guess.

**Comment by NicoVIII** [comment]
Ah, i see. The WATCH thingy was introduced in 0.13.1. That could explain why it does not work for you ^.^
https://github.com/ionide/Fornax/releases/tag/0.13.1

**Comment by AngelMunoz** [comment]
yup, you were right I'm sorry  I forgot that we set the local tools for that same reason 😅

**Pull request merged**
